In [1]:
import jieba as jb
import pandas as pd
import numpy as np
import chardet
import csv
import re

In [2]:
df = pd.read_csv('data/data.CSV', encoding='utf-8',header=None)
#y = dy.as_matrix()

In [3]:
words_in_text = []
labels = []
for i in range(len(df)):
    words_in_text.append(df.iloc[i,0])
    if i < 10001:
        df.iloc[i,1]=0
        labels.append(df.iloc[i,1])
    else:
        df.iloc[i,1]=1
        labels.append(df.iloc[i,1])
    
temp = ""
for i in range(len(df)):
    temp = (str(words_in_text[i]))
    temp = ''.join([j for j in temp if not j.isdigit()])
    temp = re.sub("[\u0060|\u0021-\u002c|\u002e-\u002f|\u003a-\u003f|\u2200-\u22ff|\uFB00-\uFFFD|\u2E80-\u33FF|\"|\“]", '', temp)
    words_in_text[i] = temp
    temp = ""
    
#print(words_in_text[0])
#print(labels[10000])

In [4]:
wordlist = []
for i in range(len(df)):
    seg_list = jb.cut(words_in_text[i], cut_all=False)
    wordlist.append("/".join(j for j in seg_list))

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\lenovo\AppData\Local\Temp\jieba.cache
Loading model cost 1.252 seconds.
Prefix dict has been built succesfully.


In [5]:
words_in_text = [[i for i in ii.split('/')] for ii in wordlist]
print(words_in_text[0])

['基金', '定', '投', '的', '锦囊妙计', '□', '上', '投', '摩根', '基金', '李佳', '读者', '定', '投有', '什么', '技巧', '定', '投', '的', '钱', '如果', '需要', '使用', '应该', '采用', '怎样', '的', '赎回', '策略', '上', '投', '摩根', '定', '投说', '起来', '简单', '但是', '仍', '有', '不少', '技巧', '如何', '开始', '定', '投', '首先', '根据', '您', '的', '投资', '目标', '投资', '年限', '以及', '您', '家庭', '收入支出', '的', '情况', '确定', '每期', '投资', '金额', '制订', '定', '投', '计划', '然后', '选择', '中长期', '业绩', '良好', '的', '两三只', '基金', '组成', '基金', '组合', '如果', '您', '的', '定', '投', '计划', '在', '年', '以上', '那么', '建议', '选择', '股票', '型基金', '最后', '即', '办理', '定', '投', '签约', '手续', '当然', '定', '投', '并非', '让', '您', '捂着', '不', '动', '投资者', '可以', '根据', '情况', '对', '扣款', '的', '金额', '所定', '投', '的', '基金', '进行', '调整', '随着', '就业', '时间', '拉长', '收入', '提高', '个人', '或', '家庭', '的', '每月', '可', '投资', '总金额', '也', '随之', '提高', '可以', '通过', '提高', '每月', '扣款', '额度', '来', '缩短', '投资', '期间', '提高', '投资', '效率', '在', '整个', '定', '投', '过程', '中', '投资者', '还是', '应该', '定期', '检视', '投资', '组合', '的', '有效性', '依照', '重点', '潜力', '市场', '分配', '不同', '的', 

In [6]:
#csvFile = open("data/data.CSV", "w")
#writer = csv.writer(csvFile)
#for i in range(len(df)):
#    writer.writerow(wordlist[0])
#csvFile.close()

In [7]:
from collections import Counter#每个词出现次数
new_token_counter=Counter(token for sentences in words_in_text for token in sentences)#多重for循环
new_top30=new_token_counter.most_common()[:30]
for index, tok in enumerate(new_top30):#穷举list并伴随一个数字index  不用index的话直接for tok in new_top30:效果相同
    print('{:>10}  freq: {:>7}'.format(tok[0], tok[1]))

         的  freq:  550125
         在  freq:  117273
        基金  freq:   98367
         了  freq:   83526
         是  freq:   75682
         ”  freq:   72032
         和  freq:   61035
        游戏  freq:   53357
         也  freq:   47827
         将  freq:   44712
        市场  freq:   42539
         月  freq:   41016
         有  freq:   39709
         为  freq:   38251
         中  freq:   38139
        玩家  freq:   33276
        公司  freq:   32854
         对  freq:   29887
         年  freq:   28306
         而  freq:   27598
         上  freq:   25643
         与  freq:   25637
         都  freq:   25489
         日  freq:   24624
         就  freq:   23419
        投资  freq:   23027
         等  freq:   22620
         但  freq:   22066
        可以  freq:   21807
         不  freq:   21795


In [8]:
#for tok in new_token_counter.most_common():#穷举list并伴随一个数字index  不用index的话直接for tok in new_top30:效果相同
    #print('{:>10}  freq: {:>7}'.format(tok[0], tok[1]))

In [9]:
stopwords=pd.read_csv('data/stopwords1.csv',encoding='utf-8',header=0)
stop_words=[]
num=0
for i in range(len(stopwords)):
    stop_words.append(stopwords.iloc[i,0])
for tok in new_token_counter.most_common():
    if len(tok[0])==1:
        stop_words.append(tok[0])###############################停用词可调
        num+=1
        if num==90:
            break

In [10]:
%%time
def clean_text(tokenized_list):
    new_list = []
    for doc in tokenized_list:
        new_list.append([token for token in doc
                         if token not in stop_words 
                         and token != ''])
    return new_list
cleaned = clean_text(words_in_text)

Wall time: 5min 12s


In [11]:
from collections import Counter
new_token_counter = Counter(token for sentences in cleaned for token in sentences)
new_top30 = new_token_counter.most_common()[:30]
for index, tok in enumerate(new_top30):
        print('{:>10}  freq: {:>7}'.format(tok[0], tok[1]))

        基金  freq:   98367
        游戏  freq:   53357
        市场  freq:   42539
        玩家  freq:   33276
        公司  freq:   32854
        投资  freq:   23027
        中国  freq:   19757
        期货  freq:   17484
        价格  freq:   15208
        产品  freq:   14773
        活动  freq:   13268
        国内  freq:   13096
        美元  freq:   12808
        上涨  freq:   12729
       投资者  freq:   12123
        记者  freq:   11321
        经济  freq:   11312
        网游  freq:   11143
        指数  freq:   10642
        银行  freq:   10500
        行业  freq:   10139
        股票  freq:   10065
        企业  freq:    9850
        显示  freq:    9829
        影响  freq:    9458
        时间  freq:    9456
        下跌  freq:    9400
        全球  freq:    9143
        世界  freq:    8915
        管理  freq:    8889


In [12]:
from gensim import corpora

dictionary = corpora.Dictionary(cleaned)

F:\tools\python\lib\site-packages\gensim\utils.py:1209: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [13]:
n = 2
corpus = [dictionary.doc2bow(text) 
          for text in cleaned]
print('Bag of Words :\n {}'.format(
    [(dictionary[i[0]], i[1]) 
     for i in corpus[n]]))
print(corpus[n])

Bag of Words :
 [('基金', 18), ('投资', 1), ('转换', 2), ('上海', 1), ('业内人士', 1), ('中心', 1), ('咨询', 1), ('有限公司', 1), ('管理', 1), ('记者', 1), ('银行', 2), ('预计', 1), ('A股', 1), ('三种', 1), ('三类', 1), ('上市', 4), ('下单', 1), ('不同于', 1), ('专家', 1), ('专电', 1), ('业内', 1), ('两种', 2), ('为数不多', 1), ('买到', 1), ('交易', 3), ('交易日', 1), ('产品', 3), ('亿元', 1), ('介绍', 1), ('代码', 2), ('以内', 1), ('份额', 14), ('公司', 1), ('公开', 1), ('内地', 1), ('内置', 1), ('分为', 2), ('分区', 1), ('分级', 4), ('创新', 1), ('创新型', 1), ('券商', 2), ('募集', 1), ('包括', 1), ('发售', 1), ('发行', 4), ('发行期', 1), ('只能', 1), ('各大', 1), ('启动', 1), ('国投', 4), ('场内', 2), ('场内外', 1), ('场外', 1), ('场所', 1), ('基金业', 1), ('境内', 2), ('外', 1), ('多重', 2), ('套利', 2), ('封', 1), ('封闭式', 1), ('将来', 1), ('小康', 3), ('工行', 1), ('平抑', 1), ('年末', 1), ('建行', 1), ('开通', 1), ('很大', 1), ('成立', 1), ('打包', 1), ('抑制', 1), ('投资人', 3), ('折', 1), ('折价', 2), ('折算', 1), ('拆', 1), ('招行', 1), ('持有', 1), ('指数', 5), ('排除', 1), ('提前结束', 1), ('提醒', 1), ('支持', 1), ('新华网', 1), ('新股', 1), ('方式', 1), 

In [14]:
n=7
from gensim import corpora, models
tfidf = models.TfidfModel(corpus)
print('TF-IDF scores : \n{}'.format(
    [(dictionary[i[0]], round(i[1],3)) 
     for i in tfidf[corpus[n]]]))

TF-IDF scores : 
[('业绩', 0.022), ('基金', 0.314), ('情况', 0.007), ('收入', 0.056), ('随之', 0.019), ('业内人士', 0.024), ('东方', 0.051), ('中心', 0.012), ('位于', 0.017), ('依然', 0.011), ('利润', 0.058), ('去年', 0.038), ('增加', 0.016), ('增幅', 0.071), ('幅度', 0.063), ('年底', 0.014), ('影响', 0.007), ('显示', 0.052), ('管理', 0.1), ('经理', 0.032), ('经营', 0.015), ('上市', 0.011), ('业内', 0.014), ('亿元', 0.107), ('份额', 0.028), ('公司', 0.135), ('公开', 0.027), ('发行', 0.021), ('年末', 0.036), ('成立', 0.011), ('此前', 0.047), ('渠道', 0.055), ('程度', 0.034), ('下降', 0.072), ('减少', 0.022), ('创出', 0.017), ('创造', 0.013), ('历史', 0.011), ('变动', 0.035), ('同比', 0.183), ('呈现', 0.038), ('国内', 0.007), ('增长', 0.095), ('大幅', 0.042), ('年度', 0.105), ('指标', 0.016), ('数据', 0.015), ('新高', 0.014), ('更是', 0.045), ('盈利', 0.014), ('相比', 0.023), ('竞争', 0.016), ('超过', 0.015), ('趋势', 0.033), ('净值', 0.012), ('分析师', 0.011), ('并未', 0.014), ('指出', 0.011), ('方向', 0.013), ('牛', 0.02), ('达', 0.04), ('风险', 0.009), ('高达', 0.033), ('人士', 0.01), ('制度', 0.016), ('发布', 0.02

In [15]:
#for n in range(len(df)):    
      #  print('TF-IDF scores: \n{}'.format([(dictionary[i[0]],round(i[1],3))for i in tfidf[corpus[n]]]))

In [16]:
%%time
important_words=[]
for i in range(len(df)):
    for j in tfidf[corpus[i]]:
       # if j[1]> 0.81:########################################可调
              # important_words.append(dictionary[j[0]])
        if j[1]<0.2694:
            if j[1]>0.268:
                important_words.append(dictionary[j[0]])
important_words =list(set(important_words))#变成set可以剔除重复项，变成list才能处理
print(important_words)
print(len(important_words))

['固定', '东军', '解封', '减仓', '朱宇琛', '上榜', '革新', '重启', '误区', 'FPS', '咖', '大亨', '中证', '球队', '申购', '品种', '精灵', '乐元', '亿份', '寄生前夜', '世代', '梦幻', '桃花源记', '下调', 'WarnerBrosInteractiveEntertainment', '万手', '监狱', '时空', '石基', 'ALP', 'GB', '欧洲', '卡', '良运', '泉州市', '杨', '淘汰赛', '阶', '风暴', '比价', '一对', '含同', '排球', '型', '流入', '单周', '角色', 'COD', '剑圣', '神行', '亿元', '爱秀小窝', '托市', '稳健', '外传', '万户', '火瀑', '孵化', '地下城', '名字', '信条', '金条', '各派', '挑战王', '嘉年华', '拟任', '英雄', '俱乐部', '活动', '汇率', '收储', '百雀灵', '之锚', '协会', '诱发', '荣誉', '电视', '糖', '网吧', 'BASARA', '政府', '第一季度', '长城', '美食', '油价', '飞行', '产量', '神鬼', '王之怒', '掌上明珠', '浩劫', '汽车', '焦炭', '匡匡', '为升', '原声', '优选', '投', '时个', '分级', '万圣节', '神兵', '晨星', '小丑', '易涨', 'VisceralGames', '练级', '山寨', '外资银行', '街霸', 'wapcn', 'NDS', 'boss', '深', '球员', 'M', '万桶', '热血', '伊儿', '吨', '三季度', 'OL', '南方', '高清', '芯片', '申请', '万吨', '举证', '创新', '大周', '收益', '堂', '江湖', '套房', '销售', '礼包', '良渚', '德鲁奥', '客服', '收藏', '欧元', 'PubQuiz', '恒信', '全景网', '棉花价格', '网上', '华', '机遇', 'Colourfulgame', '许科', '神秘', '天地', 

In [17]:
text={}
index=0
for word in important_words:
    text[word]=index
    index+=1
print(text)

{'固定': 0, '东军': 1, '解封': 2, '减仓': 3, '朱宇琛': 4, '上榜': 5, '革新': 6, '重启': 7, '误区': 8, 'FPS': 9, '咖': 10, '大亨': 11, '中证': 12, '球队': 13, '申购': 14, '品种': 15, '精灵': 16, '乐元': 17, '亿份': 18, '寄生前夜': 19, '世代': 20, '梦幻': 21, '桃花源记': 22, '下调': 23, 'WarnerBrosInteractiveEntertainment': 24, '万手': 25, '监狱': 26, '时空': 27, '石基': 28, 'ALP': 29, 'GB': 30, '欧洲': 31, '卡': 32, '良运': 33, '泉州市': 34, '杨': 35, '淘汰赛': 36, '阶': 37, '风暴': 38, '比价': 39, '一对': 40, '含同': 41, '排球': 42, '型': 43, '流入': 44, '单周': 45, '角色': 46, 'COD': 47, '剑圣': 48, '神行': 49, '亿元': 50, '爱秀小窝': 51, '托市': 52, '稳健': 53, '外传': 54, '万户': 55, '火瀑': 56, '孵化': 57, '地下城': 58, '名字': 59, '信条': 60, '金条': 61, '各派': 62, '挑战王': 63, '嘉年华': 64, '拟任': 65, '英雄': 66, '俱乐部': 67, '活动': 68, '汇率': 69, '收储': 70, '百雀灵': 71, '之锚': 72, '协会': 73, '诱发': 74, '荣誉': 75, '电视': 76, '糖': 77, '网吧': 78, 'BASARA': 79, '政府': 80, '第一季度': 81, '长城': 82, '美食': 83, '油价': 84, '飞行': 85, '产量': 86, '神鬼': 87, '王之怒': 88, '掌上明珠': 89, '浩劫': 90, '汽车': 91, '焦炭': 92, '匡匡': 93, '为升': 94, '原声': 9

In [18]:
#生成词向量
import numpy as np
feature_text = np.zeros((len(df),len(text)))
for i in range(len(df)):
    for word in words_in_text[i]:
        if word in important_words:
            feature_text[i,text[word]]+=1
print(feature_text)
print(feature_text.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(20001, 464)


In [19]:
label = np.array(labels)
#label = np.asmatrix(labels).T

In [20]:
%%time
accuracy={}
precision = {}
recall = {}
f1 = {}
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics
seed = 42
x_train, x_test, y_train, y_test = train_test_split(feature_text , label, test_size=0.33, random_state=seed)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model = model.fit(x_train, y_train)
y_pred = model.predict(x_test)

accuracy = metrics.accuracy_score(y_test.ravel(), y_pred.ravel())
precision = metrics.precision_score(y_test.ravel(), y_pred.ravel())
recall = metrics.recall_score(y_test.ravel(), y_pred.ravel())
f1 = metrics.f1_score(y_test.ravel(), y_pred.ravel())
print('Accuracy= {:.4f} | Precision= {:.4f} | Recall= {:.4f} | f1 score= {:.4f}'.format(accuracy,precision,recall,f1,))

(13400, 464) (6601, 464) (13400,) (6601,)
Accuracy= 0.9835 | Precision= 0.9748 | Recall= 0.9924 | f1 score= 0.9835
Wall time: 353 ms


In [21]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                     hidden_layer_sizes=(5, 2), random_state=1)
#
X = feature_text.astype(np.float)
Y = label.astype(np.float)

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.5,random_state=50)
clf.fit(X_train,Y_train.astype('int'))
print(clf.score(X_test,Y_test.astype('int')))
print(clf.coefs_)

0.9802019798020198
[array([[-0.00204911, -0.05473467,  0.87503576,  0.90069854,  0.41811807],
       [-0.09221647, -0.07108626, -0.03503951, -0.02072706,  0.00637236],
       [-0.22241795, -0.14819704, -0.06794273,  0.09315911, -0.10660741],
       ...,
       [-0.01745986,  0.09651026,  0.03184828, -0.02135999,  0.01584625],
       [-0.04877966,  0.00535771,  0.00722666, -0.03362137,  0.00096584],
       [-0.01706656,  0.09869648, -0.00403227,  0.02250747,  0.06350878]]), array([[-1.47113713,  2.22747047],
       [-2.83089687, -0.66244631],
       [-1.23749906,  2.98078836],
       [ 3.87336803, -1.62355176],
       [-1.72999741,  1.65969719]]), array([[ 4.84503153],
       [-3.10036745]])]


In [22]:
from sklearn import tree
treeclf = tree.DecisionTreeClassifier(criterion='gini')
treeclf.fit(X_train,Y_train)
test_accuracy = treeclf.score(X_test,Y_test)
print(test_accuracy)

0.966003399660034


In [23]:
%%time
n = 20
wid = 3
from nltk.corpus import gutenberg
from gensim import models
model = models.Word2Vec(cleaned,
                        size = n,
                        window = wid,
                        min_count = 0,
                        sg = 0,
                        alpha = 0.05,
                        iter=10,
                        batch_words = 10000)

Wall time: 1min 7s


In [25]:
import numpy as np
np.seterr(divide='ignore', invalid='ignore')
new_title_vectors= np.zeros((len(df), n))
for i in range(len(df)):
    if len(cleaned[i]) != 0:
        for word in cleaned[i]:
            new_title_vectors[i] += model.wv[word]
new_title_vectors.shape

(20001, 20)

In [26]:
final_feature = pd.DataFrame(new_title_vectors)
train = pd.concat([final_feature], axis=1)

In [27]:
%%time
#run logistic regression on feature_text
accuracy={}
precision = {}
recall = {}
f1 = {}
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics
seed = 42
x_train, x_test, y_train, y_test = train_test_split(train , label, test_size=0.2, random_state=seed)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model = model.fit(x_train, y_train)

y_pred = model.predict(x_test)

accuracy = metrics.accuracy_score(y_test.ravel(), y_pred.ravel())
precision = metrics.precision_score(y_test.ravel(), y_pred.ravel())
recall = metrics.recall_score(y_test.ravel(), y_pred.ravel())
f1 = metrics.f1_score(y_test.ravel(), y_pred.ravel())
print('Accuracy= {:.4f} | Precision= {:.4f} | Recall= {:.4f} | f1 score= {:.4f}'.format(accuracy,precision,recall,f1,))

(16000, 20) (4001, 20) (16000,) (4001,)
Accuracy= 0.9835 | Precision= 0.9819 | Recall= 0.9849 | f1 score= 0.9834
Wall time: 217 ms


In [28]:
%%time
from sklearn import svm
clf = svm.SVC()
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)
clf.score(x_test, y_test)

print('Model Accuracy:',clf.score(x_test, y_test))

Model Accuracy: 0.4976255936015996
Wall time: 1min 49s


In [1]:
%%time
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 10)
clf = clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
clf.score(x_test, y_test)

print('Model Accuracy:',clf.score(x_test, y_test))

NameError: name 'x_train' is not defined

In [ ]:
import sys
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QAction, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot
from PyQt5.Qt import QLineEdit

class App(QWidget):

    def __init__(self):
        super().__init__()
        self.title = 'PyQt5 textbox'
        self.left = 10
        self.top = 10
        self.width = 320
        self.height = 200
        self.initUI()

    def initUI(self):
        self.setWindowTitle(self.title)
        self.setGeometry(self.left, self.top, self.width, self.height)

        # create textbox
        self.textbox = QLineEdit(self)
        self.textbox.move(20, 20)
        self.textbox.resize(280, 40)

        # Create a button in the window
        self.button = QPushButton('show text', self)
        self.button.move(20, 80)

        # connect button to function on_click
        self.button.clicked.connect(self.on_click)
        self.show()

    @pyqtSlot()
    def on_click(self):
        #改这里
        textboxValue = self.textbox.text()
        QMessageBox.question(self, "Message", '标签是:' + textboxValue, 
                             QMessageBox.Ok, QMessageBox.Ok)
        """打印完毕之后清空文本框"""
        self.textbox.setText('')

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = App()
    app.exit(app.exec_())